### ISSUE TITLE
Prevent adding of persons with 0 debt

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T17-B1/main#173]

**Comment by jelneo** [comment]
0 debt as in 0 curr debt and 0 total debt?

**Comment by khooroko** [comment]
both, unless you can add a person that does not have current = total at the start. If you can do that, then only total (i.e. add a person directly into whitelist)

**Comment by jelneo** [comment]
I think you can make such that current is zero while total is some other value
