### ISSUE TITLE
Fix using unban in masterlist view

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T17-B1/main#174]
Right now, unban takes index of blacklisted persons even when in masterlist or whitelist view. Recommended fixes: 
- Allow unban only when in blacklist view
- Let unban work in masterlist view using index from currently displayed list, with appropriate messages when trying to unban someone who is not banned

**Comment by jaivigneshvenugopal** [comment]
Yes thanks wei ping! I'm working on the second one.
