### ISSUE TITLE
No provided sample account to log into

### ISSUE THREAD

**Issue by Procrastinatus** [CS2103AUG2017-T17-B1/main#214]
Can't run any commands before logging in, can't test

**Comment by KeithSOC** [comment]
+1 Could someone provide us an account to test please :)

**Comment by Procrastinatus** [comment]
donjar found a sample account - login loanShark97 hitMeUp123

**Comment by KeithSOC** [comment]
Logged in, thanks! 
@Procrastinatus Should close this issue after the end of this session. :)

**Comment by Procrastinatus** [comment]
Leave the issue open until they officially provide an account, still unsure how the sample account was found

**Comment by KeithSOC** [comment]
@Procrastinatus True, okie! :)
