### ISSUE TITLE
Password field stays at 1 character

### ISSUE THREAD

**Issue by Procrastinatus** [CS2103AUG2017-T17-B1/main#215]
When typing the login command, sometimes the password field doesn't go beyond 1 character while typing it, happens when copy-pasting as well

![image](https://user-images.githubusercontent.com/30495039/32363079-6c31f1dc-c0a8-11e7-9856-13b33727b5fe.png)

**Comment by khooroko** [comment]
Password not going past 1 or 2 characters when typing too fast is confirmed, can be recreated by quickly typing the end of the username, the space, and the first few characters of the password.
