### ISSUE TITLE
Nearby command is not clear

### ISSUE THREAD

**Issue by donjar** [CS2103AUG2017-T17-B1/main#222]
I have no idea what the command means. I've tried them, I've checked the user guide, I've asked my friends, still no idea.

Maybe giving a more concrete example in the user guide could help. So is this "nearby" like, "nearby" in location? Or maybe "nearby" in the contact listing at the left?

**Comment by Procrastinatus** [comment]
Maybe include a diagram in UG for the nearby command. **It selects the person by index in the right panel, under the "All contacts in this area:"** section. Provide a different error message instead of "The person index provided is invalid"
