### ISSUE TITLE
Possible implementations for v1.1

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T17-B1/main#29]
1. [Viggy] Add blacklist, cleared list, overdue list, critical list. (Critical list should include the whole overdue list, or use the same list with diff internal tags) (must make sure it will be easy to transfer contacts between lists)
2. [WP] Postal code validation and grouping
3. [Law] Add fields: current amount owed, multiple phone numbers, date last cleared, lifetime owed, total days overdue, times borrowed
4. [Jel] Add password login
5. [WP] Improve UI
5a: Remove browser, replace with maps location and full info
5b: Minimise info on the cards column
6. Add add tag, filter by tags
7. Versatile Sort Command that sorts according to user's preference(sort name, sort phone, sort debt etc)

**Comment by jelneo** [comment]
for 2. I think google maps would mainly be used by the profile tab display (expands when the person card listed in the left column is clicked) which will display all the info of that person, including his/her location (that is where google maps come into play).

**Comment by khooroko** [comment]
alright edited
