### ISSUE TITLE
Considering NLP to make command inputs more intuitive

### ISSUE THREAD

**Issue by jelneo** [CS2103AUG2017-T17-B1/main#44]
How are we going to make it more intuitive?
Brandon suggested using Natty.

**Comment by jaivigneshvenugopal** [comment]
I have an idea. User will type add. This will being out Tag kind of boxes in the command result box. So there will be Name Tag, Phone Tag. you manuver between the tags using our keyboard's tab button. 

Meaning, once I type add, a few tags will populate the command result box. And the name tag will be highlighed. highlighted means anything that I type will go into that tag. pressing keyboard tab will highlight the next tag. 

if i dont want to input into the next tag, i just keyboard tab again to highlight the next tag and input. once I finish inputting, i type enter. to signal that im done with inputting

Probably none of you understood that, my mental picture might be different I'll draw it up and whatsapp!
